### ISSUE TITLE
Need a survey / feedback feature

### ISSUE THREAD

**Issue by jgonzalezmsm** [SatcherInstitute/health-equity-tracker#1205]
Add Survey to collect info about user backgrounds and what is and isn't working on the tracker for them

Proposal to add to:
- Landing page
- Download and Methodology
- About Us

flexible on how it presents - pop up? or toast notification (Ben idea). Can we add logic - only presents when user scrolls to end of page? cookie settings to only present to returning users?

**Comment by jgonzalezmsm** [comment]
Revise responses to first question:

What brought you to the Health Equity Tracker?
radial bubble options: General/Professional Interest, Covid Data, Covid-19 Vaccination Data, Mental Health Data, Social and/or Political Determinants (SPDOH) Data, Other

**Comment by benhammondmusic** [comment]
PROCESS
- Cloned original feedback component, edits are made on my clone
- publish my clone to name scoped npm package
- import my version to HET rather than the original

UPDATES
- allows vertical menu for readability of more options
- more control of styling / layout / wording
- allows unlimited changes to the number and types of questions

TO DO
- [ ] see how these altered data are received / processed by the backend dashboard and accommodate

https://user-images.githubusercontent.com/41567007/141197916-29affd27-4111-4fa9-9619-847fc1b754bb.mov
