### ISSUE TITLE
Meet with Aye and Megan for Legal Epi data

### ISSUE THREAD

**Issue by jgonzalezmsm** [SatcherInstitute/health-equity-tracker#1336]
Need to set concrete development goals. Meeting to be arranged

**Comment by jgonzalezmsm** [comment]
adding meeting to sprint

**Comment by jgonzalezmsm** [comment]
Still pending to be scheduled. JC to follow up. i believe they would like Daniel on as well so I'll schedule through Ayanna.

**Comment by benhammondmusic** [comment]
Initial sketch 

![image](https://user-images.githubusercontent.com/41567007/146946160-ee736130-60bd-449d-a4e3-b04577bd9dc3.jpeg)

**Comment by benhammondmusic** [comment]
Part A: Database of Social and Political Determinants of Health
Drop down components: Economic Stability
(The 5 broad Categories) Education
                                              Healthcare
                                                 Political Determinants: Civic engagement, Political Structure, Government Performance Indices
                                              Social Environment  
Part B: Sub issue: The Political Determinants of Health: civic participation, political structure, and government performance indicators.  
 
Part C: Civic Participation, Political Structure, and Government Performance Indicators.  
 
Part D (i) Text: In line with the categorization of the Political Determinants of Health propounded by Daniel E. Dawes, we have categorized the political determinants of health as civic participation, political structure, and government performance indicators.
Click to read more:
Civic Participation: voting is an integral part of the democratic process because it is a medium through which the will of the people is expressed. Voting and health are interlinked for the reason that disparities in voter engagement as a result of health inequities, logistic difficulties, and disenfranchisement amongst others have proven to significantly impact electoral outcomes.
Political Structure: the eligibility criteria for political office and political party affiliations determine the ways policies are framed which in turn impact health outcomes either negatively or positively. Laws touching on eligibility criteria for political office have a direct impact on persons that run for and eventually occupy political office and the archetype of policies instituted by such office holders.  
Government Performance Indicators: A strong pointer to where the heart of any administration lies is its budgetary allocations. Also, a crucial parameter for appraising how well an administration has performed is the role it has played in the delivery of quality healthcare in terms of cost, access and outcomes.
 
Part D (ii): Questions / Map Display and response to questions by state.
Question 1: Does the State law mandate paid voting leave?
Question 2:  What is the State’s dominant political party?
Question 3:  What is the state’s overall healthcare rank?
Question 4:  What is the State’s CDC budgetary allocation?
 
Part A remains the same.
Part B: Sub Issue:  Economic Stability                                                                                  
Part C: Paid Sick Leave, Unemployment, Employment, and wages
Part D (i): Text
Economic stability: Income levels and health status seem to be intricately intertwined as evidence suggests lower socio-economic status leads to poorer health outcomes.  
Click to read more…
Paid Sick Leave policies have been brought to the spotlight in recent times because they reflect the importance that policy makers attach to workplace standards and the ways those standards have been impacted by the COVID-19 pandemic.  
Unemployment has been linked to poorer physical and mental health and a higher risk of premature death. Understanding the impact of policies in this area is instrumental to identifying mitigation strategies and establishing the interconnection between unemployment and ill-health.
Employment and Wages are inextricably linked because unemployment or low-paying employment directly determines access to the resources that engender health such as quality housing, nutritious food, healthcare etc.
Part D (ii) Dropdown of Questions/ Map display and response to questions by state.
Question 1: Did the state amend its paid sick leave laws as a result of COVID-19?
Question 2: What is the state unemployment rate?
Question 3: What is the state’s national ranking by percentage change to weekly wages as a result of COVID-19?

**Comment by benhammondmusic** [comment]
Ben's thoughts on mapping the data / report categorization and structure into the existing tracker:

- Split our existing `Social & Political Determinants` category into: `Social Determinants` and `Political Determinants` or potentially other categories as needed to handle the highest-level categories. So rather than the options shown above in (A) as conditions, those would map to condition categories
- Place the 2nd-level categories shown as Sub-Options in (B) as condition dropdown options in the main madlib (A)
- Keep (B) as the population card, and perhaps populate some overlay data for the geo area that exists on ALL conditions and gives SPDOH context. This could be useful for datasets that only exist at a state level and have no demographic breakdowns
- Use (C) to display the Question dropdown (currently D-ii)
- Now that we are single-column: Map will live at the top, followed by a new text card with context from the report. 
- Prevent states from being "click to drill down" since we don't have any county level data
- Populate the data table with ALL of the information from the various questions into one table
