### ISSUE TITLE
add additional topics from UHC - target towards black history month

### ISSUE THREAD

**Issue by jgonzalezmsm** [SatcherInstitute/health-equity-tracker#1423]
Link to Google doc discussing options with team: https://docs.google.com/document/d/1jkYiLN8teOmcKU1HdJXMK5Cx0pFkUDLM4a1UonYjbrg/edit

**Comment by benhammondmusic** [comment]
Based on initial feedback, narrowed to:

## Chronic Disease

* Asthma: Percentage of adults who reported being told by a health professional that they currently have asthma
* Cardiovascular disease: Percentage of adults who reported being told by a health professional that they had angina or coronary heart disease; a heart attack or myocardial infarction; or a stroke
* Chronic Kidney Disease: Percentage of adults who reported being told by a health professional that they have kidney disease not including kidney stones, bladder infection or incontinence

## Social / Political Determinant 

* Avoided Care due to Costs: Percentage of adults who reported a time in the past 12 months when they needed to see a doctor but could not because of cost
* Preventable Hospitalizations: Discharges following hospitalization for diabetes with short- or long-term complications, uncontrolled diabetes without complications, diabetes with lower-extremity amputation, chronic obstructive pulmonary disease, angina without a procedure, asthma, hypertension, heart failure, dehydration, bacterial pneumonia or urinary tract infection per 100,000 Medicare beneficiaries ages 18 and older continuously enrolled in Medicare fee-for-service Part A
