### ISSUE TITLE
Consider Age-Adjusting other conditions (e.g. diabetes, copd)

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1467]
Currently we are implementing #1459 

If we can source the needed data, it would benefit equitable representation to expand our age-adjusted ratio calculations beyond COVID deaths and hospitalizations to include other conditions that disproportionately affect minority racial/ethnic groups.

**Comment by jgonzalezmsm** [comment]
Pending guidance from Ebony - which conditions should be age-adjusted. Once we know by topic, we can categorize into three groups:

1) should be age-adjusted, learn if we have the data needed (add to roadmap).
2) should be age-adjusted, but we do not have the data (include infobox why missing data is a problem) or
2) should not be age-adjusted, (include infobox as to why its not needed).

**Comment by jgonzalezmsm** [comment]
Per Ebony (**bolded**)

Currently Age-Adjusted:
Covid Deaths
Covid Hosp
 
Not Yet Age Adjusted **(but appropriate if data were available): (You could do all of these, but aren’t completely necessary)**
Diabetes? **(This could be age-adjusted, but…isn’t necessary unless we have info on Type 1 or Type 2 diabetes in the set)**
Chronic Kidney Disease?
Cardiovascular Disease? **(could be age-adjusted since it is less likely that a young adult for example would have a heart attack)**
COPD?
Asthma? **(This could be age – adjusted since children are more likely to continue to have asthma symptoms, but isn’t necessary)**
 
Age Adjustment N/A:
Covid cases
covid vaccinations **(may need to be age-adjusted since under 5 are still not eligible, but can still get COVID)**
voter participation
care avoidance?
preventable hospitalizations?
depression?
excessive drinking?
frequent mental distress?
suicide?
illicit opioid use / non-rx opioid use / substance misuse
poverty
uninsurance

**Comment by jgonzalezmsm** [comment]
Can we age adjust any other topics?

Per Josh

Poverty
Uninsurance

only two topics that we have data on currently.

okay holding on this
