### ISSUE TITLE
ACS Population Aggregation

### ISSUE THREAD

**Issue by jenniebrown** [SatcherInstitute/health-equity-tracker#148]
This is a tracking issue for identifying and writing aggregation routines for ACS population/demographic data.

**Comment by aaronsn** [comment]
The initial ACS ingestion is creating several tables:
1. by race/ethnicity and state
2. by race/ethnicity and county
3. by race/ethnicity and age and gender and state
4. by race/ethnicity and age and gender and county

Notes:
-  I'm outputting the most granular age brackets that ACS has, and I'm also including all options for race/ethnicity that we may need.
- I'm outputting "Total" for race/ethnicity along with the actual breakdowns because the sum of the parts does not equal Total, so it's good to have the Total there
- ACS has more granular age brackets when just breaking down by sex/age than it does when breaking down by sex/age/race.

Preaggregations that would be good to have (we may need more at some point but this will be a good start):
1. by sex/age with 10-year age brackets (0-9, 10-19). This can't be done by race because they don't have brackets that work for those, so this will need to filter to "Total" and then change the brackets
2. by sex/age/race with the following brackets: 0-9, 10-17, 18-24, 25-34, 35-44, 45-54, 55-64, 65-74, 75-84, 85+
3. same thing as 1 but without sex
4. same thing as 2 but without sex
5. by sex
6. same as all 5 of the above but at the national level

@mayaspivak

**Comment by aaronsn** [comment]
Finished in pr/190. Haven't done the national level yet, will file an issue for that as a followup since there are some subtleties there that need more thought (and right now we have that being done on the frontend and it's working fine)
