### ISSUE TITLE
Discussion: Lets get rid of the county level maps

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#1711]
**Is your feature request related to a problem? Please describe.**
A main selling point of the health equity tracker is that we have lots of high quality county level data that is otherwise hard to find. Such as COVID and prison demographic data. 

However, when you click on a county level page, you don't see any of this data "above the fold", that is before you scroll down. Rather you see the top of a visualization of the county, just showing you the total incidence rate. 

Here is an example, hiding all of the interesting COVID demographic data we have.

<img width="1021" alt="Screen Shot 2022-07-22 at 4 31 28 PM" src="https://user-images.githubusercontent.com/3689026/180557853-c9a0a9bb-2bbc-44bd-981a-52f8426b0eb2.png">

**Describe the solution you'd like**
I think we should remove the map on the county level and rather show the user the per_100k in that place.

We will have to examine what this means for compare modes.

**Additional context**
This becomes even more important once we have time tracking, as that will be a compelling image we can show to the user.

**Comment by benhammondmusic** [comment]
Closing as I think the solution here is less about hiding low info maps, and more about adding better quality info to those maps. An ongoing discussion has been that we should be mapping _inequity_ rather than just disease rate. that is one possible way forward, along with adding more geographic context beyond SVI and population to the map. 

Another main reason to keep the map is that is helps orient the user, as by the time they reach a county level page they already seen (usually) the national and state parent pages. a consistent layout, particulalrly for the very first viz, seems like it's helpful.

Some items were addressed in #1233
