### ISSUE TITLE
Age-Adjusted Card should not show "Unknown Race"

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1915]
**Describe the bug**

The age-adjusted ratio card is showing a row for "Unknown Race"

**To Reproduce**
1. Go to https://healthequitytracker.org/exploredata?mls=1.covid-3.00&mlp=disparity&demo=age&dt1=deaths#age-adjusted-risk

**Expected behavior**

We will never have a ratio calculated for "Unknown Race"; it should be suppressed in the MetricQuery maybe?

This is how we suppress unwanted races on the TrendChart:

```
  const breakdowns = Breakdowns.forFips(props.fips).addBreakdown(
    props.breakdownVar,
    exclude(NON_HISPANIC, AIAN_API, UNKNOWN_RACE)
  );
```

**Screenshots**

<img width="1267" alt="Screen Shot 2022-12-01 at 8 29 30 PM" src="https://user-images.githubusercontent.com/41567007/205208900-72dc1572-6903-4063-9176-89a2c955f339.png">

**Comment by joshzarrabi** [comment]
This is interesting because we do not see the same issue when looking at this card when the `race` demographic is selected. 

https://healthequitytracker.org/exploredata?mls=1.covid-3.00&mlp=disparity&demo=race_and_ethnicity&dt1=deaths#age-adjusted-risk

<img width="1235" alt="Screen Shot 2022-12-05 at 11 57 08 AM" src="https://user-images.githubusercontent.com/3689026/205696354-ca4087df-e7c0-45d0-a7d8-b92657f74b01.png">
