### ISSUE TITLE
Still having issues with map colors on multimap view

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#2711]
### Describe the bug

When viewing county-level data in the MultiMapDialog, there is a discrepancy between the displayed map colors and the corresponding prevalence rates. This issue occurs when the map displays a single color when viewing county-level data. The problem affects all three demographic breakdowns: race, age, and sex.

### Steps to reproduce

1. Navigate to the Explore the Data page.
2. Select a topic. 
3. Select county-level data. 
4. Choose any demographic breakdown (race, age, or sex).
5. Access the MultiMapDialog.
6. [LInk to the issue](https://healthequitytracker.org/exploredata?mls=1.hiv-3.24005&mlp=disparity&dt1=hiv_prevalence&group1=All&group2=All&multiple-maps=true)

### Expected behavior

The map colors should accurately reflect the prevalence rates for the selected demographic breakdown and county. Each color on the map legend should correspond to the correct prevalence rate range.

**Screenshots**

<img width="1792" alt="Screenshot 2024-01-05 at 12 21 37 PM" src="https://github.com/SatcherInstitute/health-equity-tracker/assets/41567007/a70c593c-c288-45f5-838c-ce955d9c0a91">

**Comment by eriwarr** [comment]
# Additional Information

After further review, it appears that this issue is related to the number of values (maps) within the domain of the color scale. The current color scale accommodates up to 6 colors, corresponding to 6 values (maps). The colors are displayed accurately when there are six or fewer values (maps) within the domain.

However, the problem arises when more than six values (maps) are in the domain. In such cases, the color mapping becomes inaccurate, and incorrect colors are applied. This behavior has been observed consistently when viewing county-level data, regardless of the demographic breakdown selected (race, age, or sex).
