### ISSUE TITLE
Consider automatically chunking county-level datasets into one file per state for performance

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#305]
Likely most state-level datasets will be small enough we can use them directly (potentially with the exception of state-level time-series data, but we can cross that bridge when we come to it). However, county-level data may be too big to request all at once. Because we only need county-level data filtered to one state at a time, we can have the exporter automatically chunk county-level datasets into one file per state, for example `acs_population-by_race_county_01.json`, `acs_population-by_race_county_04.json`, etc, where the suffix is the state FIPS code. We don't currently have any county-level datasets ready except population, so we should probably wait until we have something before doing this.

@vanshkumar FYI

**Comment by aaronsn** [comment]
One thing that will need to be addressed if we do this is how to handle this in the data downloads page. For download, it seems less ideal to chunk the file and force the user to pick between 50 files, so we'd probably want to map the chunked file to a base file that is used for downloads

**Comment by aaronsn** [comment]
Discussed with Larry - confirmed that if we chunk the files we'll want to only show the unchunked version for download

**Comment by vanshkumar** [comment]
Moving performance issues to backlog as perf seems fine for launch

**Comment by joshzarrabi** [comment]
Some notes on this based on our load testing experience. 

I think we should prioritize this, first for the `acs_population-by_race_county` dataset because when we hit the server with a large number of requests we saw this dataset become a pretty bad bottleneck. 

The first requests would take a long time (a few seconds), which would lock up the current containers, cause more containers to have to be spun up to handle the other requests, which would drive up the average length of a request to get this dataset to 27 seconds, and cause an expensive container spike. If we split the dataset into counties we can avoid this lockout and keep the average request fast.
