### ISSUE TITLE
Don't join with population data for "Other"

### ISSUE THREAD

**Issue by jenniebrown** [SatcherInstitute/health-equity-tracker#309]
The CTP metadata currently has a "defines_other" column which indicates whether a state specifies what race categories are included in their "Other Race" designation. However, it doesn't indicate what those definitions are. What we need is a way to determine whether a state's "Other Race" category matches the ACS "Some other race" category for population data. Without this information, we can't know whether comparisons against the ACS's "other" categories are valid.

**Comment by aaronsn** [comment]
By the way, this may be relevant for other datasets too. If a dataset has an "other" category that includes more races than ACS's "other" category, then we can't compare them, unless we were to make additional categories. For example, if a dataset includes pacific islander in "other", then we could make an ACS category like "pacific islander or other race" and then we could join. Otherwise, we'd have to just avoid joining those categories altogether (which isn't ideal but is better than an inaccurate join).

A simple solution to this that accomplishes the bare minimum of avoiding bad data is using two different "other" designations in our [Race enum](https://github.com/SatcherInstitute/health-equity-tracker/blob/1f0cfa76f025cf51b34baf718e2d1f7295d7bced/python/ingestion/standardized_columns.py#L16):
1. OtherStandard (other defined in the same way as ACS)
2. OtherNonstandard (other defined in some different way)

If we are unable to determine which races the dataset/state includes in "other", we use OtherNonstandard to be safe.

**Comment by vanshkumar** [comment]
Making this issue more general as it applies to all datasets; for MVP we will exclude per-population metrics for "other" from the FE (or avoid doing the join on the BE, either works)

**Comment by joshzarrabi** [comment]
Because we are using the `Some Other Race Alone` categorization for `ACS Health Insurance`,  `ACS Household Income` and `ACS Population`, and they can respectively be found at `C27001F`, `B19037F`, and `B01001F` in the [groups API definition table](https://api.census.gov/data/2019/acs/acs1/groups.html), I am going to mark all of those as `OTHER_STANDARD` and the rest of the "Other" race categorizations as `OTHER_NONSTANDARD` until we can get more clarity on what exactly they entail.
