### ISSUE TITLE
Fix graphql ahr; voter and preventable aren't propagating?

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#3461]

**Comment by eriwarr** [comment]
Voter participation data is available only for election years (2008, 2012, 2016, and 2020). The data is missing for non-election years, which results in null values. Let's use the voter participation rate from the most recent election year for the years between elections.

- Use 2008 data for 2008-2011.
- Use 2012 data for 2012-2015.
- Use 2016 data for 2016-2019.
- Use 2020 data for 2020-2023

**Comment by eriwarr** [comment]
So I double-checked AHR's database, and the data provides only one age breakdown category, `Ages 65-74`. Because of that, all other age categories will be null in the `age_national` and `age_state` tables. I think we should decide whether the age breakdown for Preventable Hospitalizations should be shown at all. Maybe we could do a "Senior Report" focusing on the 'Ages 65-74' category?

**Comment by benhammondmusic** [comment]
> So I double-checked AHR's database, and the data provides only one age breakdown category, `Ages 65-74`. Because of that, all other age categories will be null in the `age_national` and `age_state` tables. I think we should decide whether the age breakdown for Preventable Hospitalizations should be shown at all. Maybe we could do a "Senior Report" focusing on the 'Ages 65-74' category?

@eriwarr I believe Preventable Hospitalizations is only measuring medicare beneficiaries, so that's probably why they don't show other age groups as the data would be much more sparse. I think we can probably hide the age breakdown for now, and then yes I think we should explore doing focused reports for seniors / kids / Black / Women etc
