### ISSUE TITLE
Review whether we want retry logic for certain status codes & whether we want to log them

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#551]
Right now any non-successful status code is a permanent failure - you'll need to reload the whole page to try again. Perhaps building retry logic for stuff like 500 status codes may not be worth the maintenance cost, but we should review.

**Comment by aaronsn** [comment]
Code pointers/context:

Currently all failures are considered permanent due to this logic: https://github.com/SatcherInstitute/health-equity-tracker/blob/a5b3bcea954147e3460b21d11dc28517f0f1174a/frontend/src/data/loading/DataManager.ts#L95

Retries could be implemented at the [DataFetcher](https://github.com/SatcherInstitute/health-equity-tracker/blob/master/frontend/src/data/loading/DataFetcher.ts) level for short-term retries (like try 3 times in a row over the course of a minute), or at the DataManager level for long-term retries (like this can retry the next time it's loaded since it last failed 3 hours ago)
