### ISSUE TITLE
ACS health insurance & poverty should join with ACS pop

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#669]
Right now, total population is calculated for ACS health ins & poverty using the dataset's itself estimates of the total population with/without health insurance & above/below the poverty level. However, we have observed that there are minor differences in the population percentages we get when we use these numbers vs the ACS population dataset. We should just have ACS health ins & poverty join with ACS pop so population numbers are consistent throughout the tracker

**Comment by vanshkumar** [comment]
Since the current ACS population age bucket boundaries don't line up such that we can construct the required buckets for ACS health ins/poverty and the current total pop diffs are fairly small, we will punt on this until after launch. When we do look into this, we should look into the methodology of ACS health ins / poverty to understand why the total populations are different from the ACS population totals, and based on that decide how exactly we should join.

**Comment by aaronsn** [comment]
Re: bucket boundaries: most of them seem to work to some degree, but sometimes the buckets need to be expanded in order to line up.

For example, these buckets would work:
* Poverty: 0-4, 5-14, 15-17, 18-24, 25-34, 35-44, 45-54, etc
* Health insurance: 0-34, 35-44, 45-54, etc

Health insurance doesn't align very closely with population for younger age brackets, hence the "0-34" bucket. But technically it is possible.
