### ISSUE TITLE
Nav bar links should be buttons

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#709]
![Screen Shot 2021-04-29 at 1 00 23 PM](https://user-images.githubusercontent.com/6402808/116611168-e738b900-a8ea-11eb-8fb8-9f5f93a1cce3.png)

**Comment by kkatzen** [comment]
Notice "explore the /n data"

**Comment by kkatzen** [comment]
This was caused by PR #691

**Comment by kkatzen** [comment]
Let's see if we can attach the link to the button itself- wrapping a link around a button is the issue

**Comment by efregoso** [comment]
To clarify: we received a11y feedback that having a button within a link resulted in a double-read of the elements for screenreaders.  At the time I figured that LinkWithStickyParams should stay instead of button given how often it was used around the rest of the site for other links, thus #691 .
I can take a shot at attaching a link to the button, but I don't know if we can make it a LinkWithStickyParams.
