### ISSUE TITLE
Back button could navigated back to same tab

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#717]
If I'm on the non default tab in About Us, click to a different page then click back, I end up back on the default tab instead of the one I was on. It would be nice if it took me back to the tab i was just on

**Comment by benhammondmusic** [comment]
UC 03- Reading the What Is Health Equity > What Is Health Equity? page	Keyboard	P2	Once the back button is selected, previous to previous page is displayed to the user	"Environment:
Device: Pixel 3a xL
Android 11
Chrome 83.0.4103.106

Prerequisite: Ensure Talkback is ON
URL: https://dev.healthequitytracker.org/

Steps:
1. Launch the url in the chrome browser
2. Navigate to What Is Health Equity > What Is Health Equity? page
3. Observe the ¨Data¨ page is shown to the user and read
4. Navigate and select ¨See data sources¨ link
5. Observe the link is displayed to the user
6. Select back button
7. Observe instead of going back to ¨Data¨ screen where the ¨See data sources¨ link is selected, the control is taken to one more previous page(What is health equity?)

Actual Result: User is taken to two screens back instead of just one screen

Expected: User should be taken back to only one screen, ¨Data¨ screen should be shown to the user"
