### ISSUE TITLE
ACS: Add health insurance status at the state and county levels

### ISSUE THREAD

**Issue by katattack** [SatcherInstitute/health-equity-tracker#74]
https://www.census.gov/data/developers/data-sets.html
https://www.census.gov/acs/www/about/why-we-ask-each-question/health
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4732875

We should see if we can get age/gender/race & ethnicity breakdowns at the county level without too high of a margin of error, which should be in the ACS data itself.

**Comment by ldbnr4** [comment]
Direct link to columns: https://api.census.gov/data/2018/acs/acs5/variables.html

**Comment by aaronsn** [comment]
Going to hand this to Seth for a starter project. Here's some information to get you started:

Background on the ACS API:
- It's organized into a bajillion individual variables, each of which you can query for a particular geography (in our case, relevant geographies are state, county, and national).
- These variables are organized into groups which each have a "concept". These groups represent all combinations of some different breakdown. For example, group `C27001A` represents the concept `HEALTH INSURANCE COVERAGE STATUS BY AGE (WHITE ALONE)`. This means that every variable in the group represents health insurance coverage status for white people for a particular age group: `C27001A_003E` -> under 19 years with health insurance, `C27001A_004E` -> under 19 years without health insurance, etc.
- I've found that the best way to understand ACS variables tends to be to go to [the page that lists group metadata](https://api.census.gov/data/2019/acs/acs5/groups.html). You can browse the group concepts, and then click "selected variables" on the right side to take you to the metadata for that group, e.g. [C27001A](https://api.census.gov/data/2019/acs/acs5/groups/C27001A.html)
- ACS API calls consist of specifying a geographic level and a list of variables you want. For example: https://api.census.gov/data/2019/acs/acs5?get=NAME,C27001A_003E,C27001A_004E&for=state:* would get variables C27001A_003E and C27001A_004E for all states.
- More ACS documentation: https://www.census.gov/data/developers/data-sets/acs-5year.html, https://api.census.gov/data/2019/acs/acs5.html. We're generally using the "Detailed Tables" unless otherwise specified. They tend to have the most granular information.

Okay so more concretely for health insurance:
- There are many health-insurance related groups, but the ones we care about are the ones broken down by race/age/sex. Other breakdowns (like income, school enrollment, etc) are beyond scope for now.
- C27001A to C27001I are the groups for health insurance by age, with each group representing a different race. These will each need to be queried and then merged together
- B27001 is the group by sex and age.
- In the standardization step, you'll end up with 4 output tables: by age/race at state level, by age/race at county level, by sex/age at state level, and by sex/age at county level
- Note that the age bucket granularity is different for B27001 vs C27001A-C27001I. That's okay, we'll just need to make sure we have matching population buckets
- I wrote some [utilities that fetch/organize ACS metadata, fetch all variables for a particular group, and standardize the frame](https://github.com/SatcherInstitute/health-equity-tracker/blob/master/python/ingestion/census.py) into a format that mostly resembles what we want the output tables to look like. You should be able to use these mostly as-is, but they may need tweaking for your use case. As for how to put it all together, I'd look at the [ACS population ingestion/standardization](https://github.com/SatcherInstitute/health-equity-tracker/blob/master/python/datasources/acs_population.py), which will mirror the health insurance logic.
- Finally, in terms of what values to extract - the most important one is # of insured. We can always derive the # of uninsured or %s by comparing with population. That being said, doesn't hurt to include both # of insured and # of uninsured separately as their own columns.
